"""empty message

Revision ID: 2666213574b2
Revises: ced910d38ff0
Create Date: 2020-10-07 08:17:06.783426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2666213574b2'
down_revision = 'ced910d38ff0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_file',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('hash_md5', sa.String(length=255), nullable=True),
    sa.Column('hash_sha1', sa.String(length=255), nullable=True),
    sa.Column('hash_sha256', sa.String(length=255), nullable=True),
    sa.Column('extension', sa.String(length=10), nullable=True),
    sa.Column('mimeType', sa.String(length=100), nullable=True),
    sa.Column('case_uuid', sa.String(length=256), nullable=True),
    sa.Column('created_by_uuid', sa.String(length=255), nullable=True),
    sa.Column('updated_by_uuid', sa.String(length=255), nullable=True),
    sa.Column('organization_uuid', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['case_uuid'], ['case.uuid'], ),
    sa.ForeignKeyConstraint(['created_by_uuid'], ['user.uuid'], ),
    sa.ForeignKeyConstraint(['organization_uuid'], ['organization.uuid'], ),
    sa.ForeignKeyConstraint(['updated_by_uuid'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.add_column('permission', sa.Column('upload_case_files', sa.Boolean(), nullable=True))
    op.add_column('permission', sa.Column('view_case_files', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permission', 'view_case_files')
    op.drop_column('permission', 'upload_case_files')
    op.drop_table('case_file')
    # ### end Alembic commands ###
