"""empty message

Revision ID: 2df7cb05f93f
Revises: 3486bf51dc65
Create Date: 2020-10-05 10:48:27.937632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2df7cb05f93f'
down_revision = '3486bf51dc65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_settings', sa.Column('assign_task_on_start', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('global_settings', 'assign_task_on_start')
    # ### end Alembic commands ###
