"""empty message

Revision ID: 30fbe40b32e9
Revises: 05f96bae63df
Create Date: 2020-10-14 09:38:34.780290

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '30fbe40b32e9'
down_revision = '05f96bae63df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'description',
               existing_type=mysql.LONGTEXT(),
               nullable=False)
    op.add_column('global_settings', sa.Column('events_per_page', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('global_settings', 'events_per_page')
    op.alter_column('event', 'description',
               existing_type=mysql.LONGTEXT(),
               nullable=True)
    # ### end Alembic commands ###
