"""empty message

Revision ID: 3486bf51dc65
Revises: f349e04a1ce9
Create Date: 2020-10-05 10:38:35.183999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3486bf51dc65'
down_revision = 'f349e04a1ce9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_settings', sa.Column('assign_case_on_create', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('global_settings', 'assign_case_on_create')
    # ### end Alembic commands ###
