"""empty message

Revision ID: 35030803cb96
Revises: b7d8a9a0953a
Create Date: 2020-10-10 15:02:31.509382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35030803cb96'
down_revision = 'b7d8a9a0953a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_note', sa.Column('after_complete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_note', 'after_complete')
    # ### end Alembic commands ###
