"""empty message

Revision ID: 39af70860e32
Revises: 1da246e2589b
Create Date: 2020-10-02 20:30:04.486070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39af70860e32'
down_revision = '1da246e2589b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('dismiss_comment', sa.Text(), nullable=True))
    op.add_column('event', sa.Column('dismiss_reason_uuid', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'event', 'close_reason', ['dismiss_reason_uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.drop_column('event', 'dismiss_reason_uuid')
    op.drop_column('event', 'dismiss_comment')
    # ### end Alembic commands ###
