"""empty message

Revision ID: 4b63d4d53a68
Revises: 2666213574b2
Create Date: 2020-10-07 11:06:39.857785

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4b63d4d53a68'
down_revision = '2666213574b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_file', sa.Column('mime_type', sa.String(length=100), nullable=True))
    op.drop_column('case_file', 'mimeType')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_file', sa.Column('mimeType', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('case_file', 'mime_type')
    # ### end Alembic commands ###
