"""empty message

Revision ID: 4c92195a5f2e
Revises: 30fbe40b32e9
Create Date: 2020-10-22 11:27:45.128515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c92195a5f2e'
down_revision = '30fbe40b32e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('source', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'source')
    # ### end Alembic commands ###
