"""empty message

Revision ID: 7001a1dd4831
Revises: f20e4a4954ef
Create Date: 2020-10-01 13:05:21.555140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7001a1dd4831'
down_revision = 'f20e4a4954ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case', sa.Column('case_template_uuid', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'case', 'case_template', ['case_template_uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'case', type_='foreignkey')
    op.drop_column('case', 'case_template_uuid')
    # ### end Alembic commands ###
