"""empty message

Revision ID: 831eee389f69
Revises: 
Create Date: 2020-09-30 12:28:18.039462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '831eee389f69'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_token_blacklist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('auth_token', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('organization',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('refresh_token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('user_uuid', sa.String(length=100), nullable=True),
    sa.Column('organization_uuid', sa.String(length=100), nullable=True),
    sa.Column('refresh_token', sa.String(length=255), nullable=True),
    sa.Column('user_agent_hash', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('agent_role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('organization_uuid', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['organization_uuid'], ['organization.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('organization_uuid', sa.String(length=255), nullable=True),
    sa.Column('add_user', sa.Boolean(), nullable=True),
    sa.Column('update_user', sa.Boolean(), nullable=True),
    sa.Column('delete_user', sa.Boolean(), nullable=True),
    sa.Column('add_user_to_role', sa.Boolean(), nullable=True),
    sa.Column('remove_user_from_role', sa.Boolean(), nullable=True),
    sa.Column('reset_user_password', sa.Boolean(), nullable=True),
    sa.Column('unlock_user', sa.Boolean(), nullable=True),
    sa.Column('view_users', sa.Boolean(), nullable=True),
    sa.Column('add_role', sa.Boolean(), nullable=True),
    sa.Column('update_role', sa.Boolean(), nullable=True),
    sa.Column('delete_role', sa.Boolean(), nullable=True),
    sa.Column('set_role_permissions', sa.Boolean(), nullable=True),
    sa.Column('view_roles', sa.Boolean(), nullable=True),
    sa.Column('create_user_group', sa.Boolean(), nullable=True),
    sa.Column('view_user_groups', sa.Boolean(), nullable=True),
    sa.Column('update_user_groups', sa.Boolean(), nullable=True),
    sa.Column('delete_user_group', sa.Boolean(), nullable=True),
    sa.Column('add_event', sa.Boolean(), nullable=True),
    sa.Column('view_events', sa.Boolean(), nullable=True),
    sa.Column('update_event', sa.Boolean(), nullable=True),
    sa.Column('delete_event', sa.Boolean(), nullable=True),
    sa.Column('add_tag_to_event', sa.Boolean(), nullable=True),
    sa.Column('remove_tag_from_event', sa.Boolean(), nullable=True),
    sa.Column('create_event_rule', sa.Boolean(), nullable=True),
    sa.Column('view_event_rules', sa.Boolean(), nullable=True),
    sa.Column('update_event_rule', sa.Boolean(), nullable=True),
    sa.Column('delete_event_rule', sa.Boolean(), nullable=True),
    sa.Column('add_observable', sa.Boolean(), nullable=True),
    sa.Column('update_observable', sa.Boolean(), nullable=True),
    sa.Column('delete_observable', sa.Boolean(), nullable=True),
    sa.Column('add_tag_to_observable', sa.Boolean(), nullable=True),
    sa.Column('remove_tag_from_observable', sa.Boolean(), nullable=True),
    sa.Column('add_playbook', sa.Boolean(), nullable=True),
    sa.Column('update_playbook', sa.Boolean(), nullable=True),
    sa.Column('delete_playbook', sa.Boolean(), nullable=True),
    sa.Column('view_playbooks', sa.Boolean(), nullable=True),
    sa.Column('add_tag_to_playbook', sa.Boolean(), nullable=True),
    sa.Column('remove_tag_from_playbook', sa.Boolean(), nullable=True),
    sa.Column('view_agents', sa.Boolean(), nullable=True),
    sa.Column('update_agent', sa.Boolean(), nullable=True),
    sa.Column('delete_agent', sa.Boolean(), nullable=True),
    sa.Column('pair_agent', sa.Boolean(), nullable=True),
    sa.Column('create_agent_group', sa.Boolean(), nullable=True),
    sa.Column('view_agent_groups', sa.Boolean(), nullable=True),
    sa.Column('update_agent_group', sa.Boolean(), nullable=True),
    sa.Column('delete_agent_group', sa.Boolean(), nullable=True),
    sa.Column('add_input', sa.Boolean(), nullable=True),
    sa.Column('view_inputs', sa.Boolean(), nullable=True),
    sa.Column('update_input', sa.Boolean(), nullable=True),
    sa.Column('delete_input', sa.Boolean(), nullable=True),
    sa.Column('add_tag', sa.Boolean(), nullable=True),
    sa.Column('update_tag', sa.Boolean(), nullable=True),
    sa.Column('delete_tag', sa.Boolean(), nullable=True),
    sa.Column('view_tags', sa.Boolean(), nullable=True),
    sa.Column('create_case', sa.Boolean(), nullable=True),
    sa.Column('view_cases', sa.Boolean(), nullable=True),
    sa.Column('update_case', sa.Boolean(), nullable=True),
    sa.Column('delete_case', sa.Boolean(), nullable=True),
    sa.Column('create_case_task', sa.Boolean(), nullable=True),
    sa.Column('view_case_tasks', sa.Boolean(), nullable=True),
    sa.Column('update_case_task', sa.Boolean(), nullable=True),
    sa.Column('delete_case_task', sa.Boolean(), nullable=True),
    sa.Column('create_case_template', sa.Boolean(), nullable=True),
    sa.Column('view_case_templates', sa.Boolean(), nullable=True),
    sa.Column('update_case_template', sa.Boolean(), nullable=True),
    sa.Column('delete_case_template', sa.Boolean(), nullable=True),
    sa.Column('create_case_template_task', sa.Boolean(), nullable=True),
    sa.Column('view_case_template_tasks', sa.Boolean(), nullable=True),
    sa.Column('update_case_template_task', sa.Boolean(), nullable=True),
    sa.Column('delete_case_template_task', sa.Boolean(), nullable=True),
    sa.Column('create_case_comment', sa.Boolean(), nullable=True),
    sa.Column('view_case_comments', sa.Boolean(), nullable=True),
    sa.Column('update_case_comment', sa.Boolean(), nullable=True),
    sa.Column('delete_case_comment', sa.Boolean(), nullable=True),
    sa.Column('create_case_status', sa.Boolean(), nullable=True),
    sa.Column('update_case_status', sa.Boolean(), nullable=True),
    sa.Column('delete_case_status', sa.Boolean(), nullable=True),
    sa.Column('view_plugins', sa.Boolean(), nullable=True),
    sa.Column('create_plugin', sa.Boolean(), nullable=True),
    sa.Column('delete_plugin', sa.Boolean(), nullable=True),
    sa.Column('update_plugin', sa.Boolean(), nullable=True),
    sa.Column('add_credential', sa.Boolean(), nullable=True),
    sa.Column('update_credential', sa.Boolean(), nullable=True),
    sa.Column('decrypt_credential', sa.Boolean(), nullable=True),
    sa.Column('delete_credential', sa.Boolean(), nullable=True),
    sa.Column('view_credentials', sa.Boolean(), nullable=True),
    sa.Column('add_organization', sa.Boolean(), nullable=True),
    sa.Column('view_organizatons', sa.Boolean(), nullable=True),
    sa.Column('update_organization', sa.Boolean(), nullable=True),
    sa.Column('delete_organization', sa.Boolean(), nullable=True),
    sa.Column('add_list', sa.Boolean(), nullable=True),
    sa.Column('update_list', sa.Boolean(), nullable=True),
    sa.Column('view_lists', sa.Boolean(), nullable=True),
    sa.Column('delete_list', sa.Boolean(), nullable=True),
    sa.Column('create_data_type', sa.Boolean(), nullable=True),
    sa.Column('update_data_type', sa.Boolean(), nullable=True),
    sa.Column('update_settings', sa.Boolean(), nullable=True),
    sa.Column('view_settings', sa.Boolean(), nullable=True),
    sa.Column('create_persistent_pairing_token', sa.Boolean(), nullable=True),
    sa.Column('use_api', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['organization_uuid'], ['organization.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('user_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('organization_uuid', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['organization_uuid'], ['organization.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('permissions_uuid', sa.String(length=255), nullable=True),
    sa.Column('organization_uuid', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['organization_uuid'], ['organization.uuid'], ),
    sa.ForeignKeyConstraint(['permissions_uuid'], ['permission.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('agent',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('ip_address', sa.String(length=255), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=True),
    sa.Column('role_uuid', sa.String(length=255), nullable=True),
    sa.Column('organization_uuid', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['organization_uuid'], ['organization.uuid'], ),
    sa.ForeignKeyConstraint(['role_uuid'], ['role.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('last_logon', sa.DateTime(), nullable=True),
    sa.Column('password_hash', sa.String(length=100), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.Column('failed_logons', sa.Integer(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('role_uuid', sa.String(length=255), nullable=True),
    sa.Column('organization_uuid', sa.String(length=255), nullable=True),
    sa.Column('api_key', sa.String(length=255), nullable=True),
    sa.Column('created_by_uuid', sa.String(length=255), nullable=True),
    sa.Column('updated_by_uuid', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['created_by_uuid'], ['user.uuid'], ),
    sa.ForeignKeyConstraint(['organization_uuid'], ['organization.uuid'], ),
    sa.ForeignKeyConstraint(['role_uuid'], ['role.uuid'], ),
    sa.ForeignKeyConstraint(['updated_by_uuid'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('agent_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_uuid', sa.String(length=255), nullable=True),
    sa.Column('updated_by_uuid', sa.String(length=255), nullable=True),
    sa.Column('organization_uuid', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['created_by_uuid'], ['user.uuid'], ),
    sa.ForeignKeyConstraint(['organization_uuid'], ['organization.uuid'], ),
    sa.ForeignKeyConstraint(['updated_by_uuid'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('agent_role_agent',
    sa.Column('agent_uuid', sa.String(length=255), nullable=True),
    sa.Column('agent_role_uuid', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['agent_role_uuid'], ['agent_role.uuid'], ),
    sa.ForeignKeyConstraint(['agent_uuid'], ['agent.uuid'], )
    )
    op.create_table('case_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('closed', sa.Boolean(), nullable=True),
    sa.Column('created_by_uuid', sa.String(length=255), nullable=True),
    sa.Column('updated_by_uuid', sa.String(length=255), nullable=True),
    sa.Column('organization_uuid', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['created_by_uuid'], ['user.uuid'], ),
    sa.ForeignKeyConstraint(['organization_uuid'], ['organization.uuid'], ),
    sa.ForeignKeyConstraint(['updated_by_uuid'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('case_template',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.Column('owner_uuid', sa.String(length=255), nullable=True),
    sa.Column('tlp', sa.Integer(), nullable=True),
    sa.Column('created_by_uuid', sa.String(length=255), nullable=True),
    sa.Column('updated_by_uuid', sa.String(length=255), nullable=True),
    sa.Column('organization_uuid', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['created_by_uuid'], ['user.uuid'], ),
    sa.ForeignKeyConstraint(['organization_uuid'], ['organization.uuid'], ),
    sa.ForeignKeyConstraint(['owner_uuid'], ['user.uuid'], ),
    sa.ForeignKeyConstraint(['updated_by_uuid'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('close_reason',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_by_uuid', sa.String(length=255), nullable=True),
    sa.Column('organization_uuid', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['created_by_uuid'], ['user.uuid'], ),
    sa.ForeignKeyConstraint(['organization_uuid'], ['organization.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('credential',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('secret', sa.String(length=2048), nullable=True),
    sa.Column('organization_uuid', sa.String(length=255), nullable=True),
    sa.Column('created_by_uuid', sa.String(length=255), nullable=True),
    sa.Column('updated_by_uuid', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['created_by_uuid'], ['user.uuid'], ),
    sa.ForeignKeyConstraint(['organization_uuid'], ['organization.uuid'], ),
    sa.ForeignKeyConstraint(['updated_by_uuid'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('data_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('regex', sa.Text(), nullable=True),
    sa.Column('created_by_uuid', sa.String(length=255), nullable=True),
    sa.Column('updated_by_uuid', sa.String(length=255), nullable=True),
    sa.Column('organization_uuid', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['created_by_uuid'], ['user.uuid'], ),
    sa.ForeignKeyConstraint(['organization_uuid'], ['organization.uuid'], ),
    sa.ForeignKeyConstraint(['updated_by_uuid'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('event_rule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_signature', sa.String(length=255), nullable=True),
    sa.Column('rule_signature', sa.String(length=255), nullable=True),
    sa.Column('target_case_uuid', sa.String(length=255), nullable=True),
    sa.Column('merge_into_case', sa.Boolean(), nullable=True),
    sa.Column('dismiss', sa.Boolean(), nullable=True),
    sa.Column('expire', sa.Boolean(), nullable=True),
    sa.Column('expire_at', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_by_uuid', sa.String(length=255), nullable=True),
    sa.Column('updated_by_uuid', sa.String(length=255), nullable=True),
    sa.Column('organization_uuid', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['created_by_uuid'], ['user.uuid'], ),
    sa.ForeignKeyConstraint(['organization_uuid'], ['organization.uuid'], ),
    sa.ForeignKeyConstraint(['updated_by_uuid'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('event_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('closed', sa.Boolean(), nullable=True),
    sa.Column('created_by_uuid', sa.String(length=255), nullable=True),
    sa.Column('updated_by_uuid', sa.String(length=255), nullable=True),
    sa.Column('organization_uuid', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['created_by_uuid'], ['user.uuid'], ),
    sa.ForeignKeyConstraint(['organization_uuid'], ['organization.uuid'], ),
    sa.ForeignKeyConstraint(['updated_by_uuid'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('playbook',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_by_uuid', sa.String(length=255), nullable=True),
    sa.Column('updated_by_uuid', sa.String(length=255), nullable=True),
    sa.Column('organization_uuid', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['created_by_uuid'], ['user.uuid'], ),
    sa.ForeignKeyConstraint(['organization_uuid'], ['organization.uuid'], ),
    sa.ForeignKeyConstraint(['updated_by_uuid'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('plugin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('logo', sa.Text(), nullable=True),
    sa.Column('manifest', sa.JSON(), nullable=False),
    sa.Column('config_template', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_hash', sa.String(length=255), nullable=True),
    sa.Column('created_by_uuid', sa.String(length=255), nullable=True),
    sa.Column('updated_by_uuid', sa.String(length=255), nullable=True),
    sa.Column('organization_uuid', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['created_by_uuid'], ['user.uuid'], ),
    sa.ForeignKeyConstraint(['organization_uuid'], ['organization.uuid'], ),
    sa.ForeignKeyConstraint(['updated_by_uuid'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('created_by_uuid', sa.String(length=255), nullable=True),
    sa.Column('updated_by_uuid', sa.String(length=255), nullable=True),
    sa.Column('organization_uuid', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['created_by_uuid'], ['user.uuid'], ),
    sa.ForeignKeyConstraint(['organization_uuid'], ['organization.uuid'], ),
    sa.ForeignKeyConstraint(['updated_by_uuid'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('user_group_assignment',
    sa.Column('user_uuid', sa.String(length=255), nullable=True),
    sa.Column('user_group_uuid', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_group_uuid'], ['user_group.uuid'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['user.uuid'], )
    )
    op.create_table('agent_group_agent',
    sa.Column('agent_uuid', sa.String(length=255), nullable=True),
    sa.Column('agent_group_uuid', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['agent_group_uuid'], ['agent_group.uuid'], ),
    sa.ForeignKeyConstraint(['agent_uuid'], ['agent.uuid'], )
    )
    op.create_table('case',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.Column('owner_uuid', sa.String(length=255), nullable=True),
    sa.Column('tlp', sa.Integer(), nullable=True),
    sa.Column('status_uuid', sa.String(length=255), nullable=True),
    sa.Column('_closed', sa.Boolean(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('close_comment', sa.Text(), nullable=True),
    sa.Column('close_reason_uuid', sa.String(length=255), nullable=True),
    sa.Column('created_by_uuid', sa.String(length=255), nullable=True),
    sa.Column('updated_by_uuid', sa.String(length=255), nullable=True),
    sa.Column('organization_uuid', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['close_reason_uuid'], ['close_reason.uuid'], ),
    sa.ForeignKeyConstraint(['created_by_uuid'], ['user.uuid'], ),
    sa.ForeignKeyConstraint(['organization_uuid'], ['organization.uuid'], ),
    sa.ForeignKeyConstraint(['owner_uuid'], ['user.uuid'], ),
    sa.ForeignKeyConstraint(['status_uuid'], ['case_status.uuid'], ),
    sa.ForeignKeyConstraint(['updated_by_uuid'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('case_template_task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('group_uuid', sa.String(length=255), nullable=True),
    sa.Column('owner_uuid', sa.String(length=255), nullable=True),
    sa.Column('case_template_uuid', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('created_by_uuid', sa.String(length=255), nullable=True),
    sa.Column('updated_by_uuid', sa.String(length=255), nullable=True),
    sa.Column('organization_uuid', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['case_template_uuid'], ['case_template.uuid'], ),
    sa.ForeignKeyConstraint(['created_by_uuid'], ['user.uuid'], ),
    sa.ForeignKeyConstraint(['group_uuid'], ['user_group.uuid'], ),
    sa.ForeignKeyConstraint(['organization_uuid'], ['organization.uuid'], ),
    sa.ForeignKeyConstraint(['owner_uuid'], ['user.uuid'], ),
    sa.ForeignKeyConstraint(['updated_by_uuid'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('global_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('base_url', sa.String(length=2048), nullable=True),
    sa.Column('require_case_templates', sa.Boolean(), nullable=True),
    sa.Column('email_from', sa.String(length=255), nullable=True),
    sa.Column('email_server', sa.String(length=255), nullable=True),
    sa.Column('email_secret_uuid', sa.String(length=255), nullable=True),
    sa.Column('allow_comment_deletion', sa.Boolean(), nullable=True),
    sa.Column('playbook_action_timeout', sa.Integer(), nullable=True),
    sa.Column('playbook_timeout', sa.Integer(), nullable=True),
    sa.Column('logon_password_attempts', sa.Integer(), nullable=True),
    sa.Column('organization_uuid', sa.String(length=255), nullable=True),
    sa.Column('api_key_valid_days', sa.Integer(), nullable=True),
    sa.Column('agent_pairing_token_valid_minutes', sa.Integer(), nullable=True),
    sa.Column('peristent_pairing_token', sa.String(length=255), nullable=True),
    sa.Column('require_event_dismiss_comment', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['email_secret_uuid'], ['credential.uuid'], ),
    sa.ForeignKeyConstraint(['organization_uuid'], ['organization.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('input',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('plugin', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('credential_id', sa.String(length=255), nullable=True),
    sa.Column('field_mapping', sa.JSON(), nullable=False),
    sa.Column('created_by_uuid', sa.String(length=255), nullable=True),
    sa.Column('updated_by_uuid', sa.String(length=255), nullable=True),
    sa.Column('organization_uuid', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['created_by_uuid'], ['user.uuid'], ),
    sa.ForeignKeyConstraint(['credential_id'], ['credential.uuid'], ),
    sa.ForeignKeyConstraint(['organization_uuid'], ['organization.uuid'], ),
    sa.ForeignKeyConstraint(['updated_by_uuid'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('list',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('list_type', sa.String(length=255), nullable=True),
    sa.Column('data_type_uuid', sa.String(length=255), nullable=True),
    sa.Column('tag_on_match', sa.Boolean(), nullable=True),
    sa.Column('organization_uuid', sa.String(length=255), nullable=True),
    sa.Column('created_by_uuid', sa.String(length=255), nullable=True),
    sa.Column('updated_by_uuid', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['created_by_uuid'], ['user.uuid'], ),
    sa.ForeignKeyConstraint(['data_type_uuid'], ['data_type.uuid'], ),
    sa.ForeignKeyConstraint(['organization_uuid'], ['organization.uuid'], ),
    sa.ForeignKeyConstraint(['updated_by_uuid'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('observable',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('dataType_id', sa.String(length=255), nullable=True),
    sa.Column('tlp', sa.Integer(), nullable=True),
    sa.Column('ioc', sa.Boolean(), nullable=True),
    sa.Column('spotted', sa.Boolean(), nullable=True),
    sa.Column('safe', sa.Boolean(), nullable=True),
    sa.Column('created_by_uuid', sa.String(length=255), nullable=True),
    sa.Column('updated_by_uuid', sa.String(length=255), nullable=True),
    sa.Column('organization_uuid', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['created_by_uuid'], ['user.uuid'], ),
    sa.ForeignKeyConstraint(['dataType_id'], ['data_type.uuid'], ),
    sa.ForeignKeyConstraint(['organization_uuid'], ['organization.uuid'], ),
    sa.ForeignKeyConstraint(['updated_by_uuid'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('plugin_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('plugin_uuid', sa.String(length=255), nullable=True),
    sa.Column('created_by_uuid', sa.String(length=255), nullable=True),
    sa.Column('updated_by_uuid', sa.String(length=255), nullable=True),
    sa.Column('organization_uuid', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['created_by_uuid'], ['user.uuid'], ),
    sa.ForeignKeyConstraint(['organization_uuid'], ['organization.uuid'], ),
    sa.ForeignKeyConstraint(['plugin_uuid'], ['plugin.uuid'], ),
    sa.ForeignKeyConstraint(['updated_by_uuid'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('tag_case_template',
    sa.Column('case_template_uuid', sa.String(length=255), nullable=True),
    sa.Column('tag_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['case_template_uuid'], ['case_template.uuid'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.uuid'], )
    )
    op.create_table('tag_organization',
    sa.Column('organization_uuid', sa.String(length=255), nullable=True),
    sa.Column('tag_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['organization_uuid'], ['organization.uuid'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.uuid'], )
    )
    op.create_table('tag_playbook',
    sa.Column('playbook_uuid', sa.String(length=255), nullable=True),
    sa.Column('tag_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['playbook_uuid'], ['playbook.uuid'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.uuid'], )
    )
    op.create_table('agent_input',
    sa.Column('agent_uuid', sa.String(length=255), nullable=True),
    sa.Column('input_uuid', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['agent_uuid'], ['agent.uuid'], ),
    sa.ForeignKeyConstraint(['input_uuid'], ['input.uuid'], )
    )
    op.create_table('case_comment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('case_uuid', sa.String(length=255), nullable=True),
    sa.Column('is_closure_comment', sa.Text(), nullable=True),
    sa.Column('closure_reason_uuid', sa.String(length=255), nullable=True),
    sa.Column('created_by_uuid', sa.String(length=255), nullable=True),
    sa.Column('updated_by_uuid', sa.String(length=255), nullable=True),
    sa.Column('organization_uuid', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['case_uuid'], ['case.uuid'], ),
    sa.ForeignKeyConstraint(['closure_reason_uuid'], ['close_reason.uuid'], ),
    sa.ForeignKeyConstraint(['created_by_uuid'], ['user.uuid'], ),
    sa.ForeignKeyConstraint(['organization_uuid'], ['organization.uuid'], ),
    sa.ForeignKeyConstraint(['updated_by_uuid'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('case_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('case_uuid', sa.String(length=255), nullable=True),
    sa.Column('created_by_uuid', sa.String(length=255), nullable=True),
    sa.Column('organization_uuid', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['case_uuid'], ['case.uuid'], ),
    sa.ForeignKeyConstraint(['created_by_uuid'], ['user.uuid'], ),
    sa.ForeignKeyConstraint(['organization_uuid'], ['organization.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('case_task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('group_uuid', sa.String(length=255), nullable=True),
    sa.Column('owner_uuid', sa.String(length=255), nullable=True),
    sa.Column('case_uuid', sa.String(length=255), nullable=True),
    sa.Column('from_template', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('created_by_uuid', sa.String(length=255), nullable=True),
    sa.Column('updated_by_uuid', sa.String(length=255), nullable=True),
    sa.Column('organization_uuid', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['case_uuid'], ['case.uuid'], ),
    sa.ForeignKeyConstraint(['created_by_uuid'], ['user.uuid'], ),
    sa.ForeignKeyConstraint(['group_uuid'], ['user_group.uuid'], ),
    sa.ForeignKeyConstraint(['organization_uuid'], ['organization.uuid'], ),
    sa.ForeignKeyConstraint(['owner_uuid'], ['user.uuid'], ),
    sa.ForeignKeyConstraint(['updated_by_uuid'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('tlp', sa.Integer(), nullable=True),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.String(length=255), nullable=True),
    sa.Column('case_uuid', sa.String(length=255), nullable=True),
    sa.Column('raw_log', sa.JSON(), nullable=True),
    sa.Column('signature', sa.String(length=255), nullable=True),
    sa.Column('organization_uuid', sa.String(length=255), nullable=True),
    sa.Column('created_by_uuid', sa.String(length=255), nullable=True),
    sa.Column('updated_by_uuid', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['case_uuid'], ['case.uuid'], ),
    sa.ForeignKeyConstraint(['created_by_uuid'], ['user.uuid'], ),
    sa.ForeignKeyConstraint(['organization_uuid'], ['organization.uuid'], ),
    sa.ForeignKeyConstraint(['status_id'], ['event_status.uuid'], ),
    sa.ForeignKeyConstraint(['updated_by_uuid'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('list_value',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('parent_list_uuid', sa.String(length=255), nullable=True),
    sa.Column('organization_uuid', sa.String(length=255), nullable=True),
    sa.Column('created_by_uuid', sa.String(length=255), nullable=True),
    sa.Column('updated_by_uuid', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['created_by_uuid'], ['user.uuid'], ),
    sa.ForeignKeyConstraint(['parent_list_uuid'], ['list.uuid'], ),
    sa.ForeignKeyConstraint(['updated_by_uuid'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('observable_case',
    sa.Column('observable_uuid', sa.String(length=255), nullable=True),
    sa.Column('case_uuid', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['case_uuid'], ['case.uuid'], ),
    sa.ForeignKeyConstraint(['observable_uuid'], ['observable.uuid'], )
    )
    op.create_table('observable_event_rule',
    sa.Column('observable_uuid', sa.String(length=255), nullable=True),
    sa.Column('event_rule_uuid', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['event_rule_uuid'], ['event_rule.uuid'], ),
    sa.ForeignKeyConstraint(['observable_uuid'], ['observable.uuid'], )
    )
    op.create_table('plugin_plugin_config',
    sa.Column('plugin_uuid', sa.String(length=255), nullable=True),
    sa.Column('plugin_config.uuid', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['plugin_config.uuid'], ['plugin_config.uuid'], ),
    sa.ForeignKeyConstraint(['plugin_uuid'], ['plugin.uuid'], )
    )
    op.create_table('tag_case',
    sa.Column('case_uuid', sa.String(length=255), nullable=True),
    sa.Column('tag_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['case_uuid'], ['case.uuid'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.uuid'], )
    )
    op.create_table('tag_input',
    sa.Column('input_uuid', sa.String(length=255), nullable=True),
    sa.Column('tag_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['input_uuid'], ['input.uuid'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.uuid'], )
    )
    op.create_table('tag_observable',
    sa.Column('observable_uuid', sa.String(length=255), nullable=True),
    sa.Column('tag_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['observable_uuid'], ['observable.uuid'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.uuid'], )
    )
    op.create_table('user_case',
    sa.Column('user_uuid', sa.String(length=255), nullable=True),
    sa.Column('case_uuid', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['case_uuid'], ['case.uuid'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['user.uuid'], )
    )
    op.create_table('event_case',
    sa.Column('event_uuid', sa.String(length=255), nullable=True),
    sa.Column('case_uuid', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['case_uuid'], ['case.uuid'], ),
    sa.ForeignKeyConstraint(['event_uuid'], ['event.uuid'], )
    )
    op.create_table('observable_event',
    sa.Column('observable_uuid', sa.String(length=255), nullable=True),
    sa.Column('event_uuid', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['event_uuid'], ['event.uuid'], ),
    sa.ForeignKeyConstraint(['observable_uuid'], ['observable.uuid'], )
    )
    op.create_table('tag_event',
    sa.Column('event_uuid', sa.String(length=255), nullable=True),
    sa.Column('tag_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['event_uuid'], ['event.uuid'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.uuid'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag_event')
    op.drop_table('observable_event')
    op.drop_table('event_case')
    op.drop_table('user_case')
    op.drop_table('tag_observable')
    op.drop_table('tag_input')
    op.drop_table('tag_case')
    op.drop_table('plugin_plugin_config')
    op.drop_table('observable_event_rule')
    op.drop_table('observable_case')
    op.drop_table('list_value')
    op.drop_table('event')
    op.drop_table('case_task')
    op.drop_table('case_history')
    op.drop_table('case_comment')
    op.drop_table('agent_input')
    op.drop_table('tag_playbook')
    op.drop_table('tag_organization')
    op.drop_table('tag_case_template')
    op.drop_table('plugin_config')
    op.drop_table('observable')
    op.drop_table('list')
    op.drop_table('input')
    op.drop_table('global_settings')
    op.drop_table('case_template_task')
    op.drop_table('case')
    op.drop_table('agent_group_agent')
    op.drop_table('user_group_assignment')
    op.drop_table('tag')
    op.drop_table('plugin')
    op.drop_table('playbook')
    op.drop_table('event_status')
    op.drop_table('event_rule')
    op.drop_table('data_type')
    op.drop_table('credential')
    op.drop_table('close_reason')
    op.drop_table('case_template')
    op.drop_table('case_status')
    op.drop_table('agent_role_agent')
    op.drop_table('agent_group')
    op.drop_table('user')
    op.drop_table('agent')
    op.drop_table('role')
    op.drop_table('user_group')
    op.drop_table('permission')
    op.drop_table('agent_role')
    op.drop_table('refresh_token')
    op.drop_table('organization')
    op.drop_table('auth_token_blacklist')
    # ### end Alembic commands ###
