"""empty message

Revision ID: a94c67faa9ea
Revises: 798c3f1b42d5
Create Date: 2020-10-05 20:17:03.838185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a94c67faa9ea'
down_revision = '798c3f1b42d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_settings', sa.Column('allow_comment_editing', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('global_settings', 'allow_comment_editing')
    # ### end Alembic commands ###
