"""empty message

Revision ID: b7d8a9a0953a
Revises: 4b63d4d53a68
Create Date: 2020-10-07 20:21:38.821877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7d8a9a0953a'
down_revision = '4b63d4d53a68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permission', sa.Column('delete_case_files', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permission', 'delete_case_files')
    # ### end Alembic commands ###
