"""empty message

Revision ID: bf16145879c8
Revises: 2df7cb05f93f
Create Date: 2020-10-05 13:32:14.889820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf16145879c8'
down_revision = '2df7cb05f93f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('notify_on_case_assign', sa.Boolean(), nullable=True),
    sa.Column('notify_on_task_assign', sa.Boolean(), nullable=True),
    sa.Column('user_uuid', sa.String(length=255), nullable=True),
    sa.Column('organization_uuid', sa.String(length=255), nullable=True),
    sa.Column('created_by_uuid', sa.String(length=255), nullable=True),
    sa.Column('updated_by_uuid', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['created_by_uuid'], ['user.uuid'], ),
    sa.ForeignKeyConstraint(['organization_uuid'], ['organization.uuid'], ),
    sa.ForeignKeyConstraint(['updated_by_uuid'], ['user.uuid'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.add_column('user', sa.Column('settings_uuid', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'user', 'user_settings', ['settings_uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'settings_uuid')
    op.drop_table('user_settings')
    # ### end Alembic commands ###
