"""empty message

Revision ID: ced910d38ff0
Revises: 5842f22334ce
Create Date: 2020-10-06 20:41:35.798377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ced910d38ff0'
down_revision = '5842f22334ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_to_case',
    sa.Column('parent_case_uuid', sa.String(length=255), nullable=True),
    sa.Column('child_case_uuid', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['child_case_uuid'], ['case.uuid'], ),
    sa.ForeignKeyConstraint(['parent_case_uuid'], ['case.uuid'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_to_case')
    # ### end Alembic commands ###
