"""empty message

Revision ID: f20e4a4954ef
Revises: 831eee389f69
Create Date: 2020-09-30 14:13:51.693634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f20e4a4954ef'
down_revision = '831eee389f69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_settings', sa.Column('require_case_close_comment', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('global_settings', 'require_case_close_comment')
    # ### end Alembic commands ###
