"""empty message

Revision ID: f349e04a1ce9
Revises: dc5e794a369e
Create Date: 2020-10-04 20:33:39.318927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f349e04a1ce9'
down_revision = 'dc5e794a369e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_note', sa.Column('finish_date', sa.DateTime(), nullable=True))
    op.add_column('task_note', sa.Column('start_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_note', 'start_date')
    op.drop_column('task_note', 'finish_date')
    # ### end Alembic commands ###
